// quests.js
// Contains sample world quests. This file must be loaded before script.js
window.questsData = [
  { id:1, category:"Travel", title:"Climb Mt. Kenya", xp:800, completed:false },
  { id:2, category:"Startup", title:"Register Nexus Creations", xp:300, completed:true },
  { id:3, category:"Startup", title:"Launch NeoAfriTech MVP", xp:1200, completed:false },
  { id:4, category:"Film", title:"Write short film script", xp:400, completed:true },
  { id:5, category:"Film", title:"Shoot short film", xp:900, completed:false },
  { id:6, category:"Film", title:"Edit and color grade film", xp:600, completed:false },
  { id:7, category:"Networking", title:"Attend regional tech meetup", xp:200, completed:true },
  { id:8, category:"Networking", title:"Host a multi-city workshop", xp:1000, completed:false },
  { id:9, category:"Personal", title:"Run 5km straight", xp:150, completed:true },
  { id:10, category:"Personal", title:"Read 12 books this year", xp:500, completed:false },
  { id:11, category:"Business", title:"Sign first SaaS client", xp:800, completed:false },
  { id:12, category:"Business", title:"Automate quoting process for Nexus", xp:350, completed:false },
  { id:13, category:"Creative", title:"Build Code-as-Art generator prototype", xp:700, completed:false },
  { id:14, category:"Learning", title:"Complete advanced JS course", xp:400, completed:true },
  { id:15, category:"Learning", title:"Master color grading", xp:300, completed:false },
  { id:16, category:"Health", title:"Join a local football team", xp:250, completed:true },
  { id:17, category:"Travel", title:"Attend an international film festival", xp:1000, completed:false },
  { id:18, category:"Community", title:"Volunteer a tech workshop in a rural school", xp:450, completed:false },
  { id:19, category:"Creative", title:"Design a visual bible for a series", xp:600, completed:false },
  { id:20, category:"Startup", title:"Build landing page for NeoAfriTech", xp:250, completed:true },
  { id:21, category:"Finance", title:"Save emergency fund (3 months)", xp:500, completed:false },
  { id:22, category:"Business", title:"Hire first contractor", xp:400, completed:false },
  { id:23, category:"Film", title:"Submit film to 5 festivals", xp:700, completed:false },
  { id:24, category:"Personal", title:"Create a consistent morning routine", xp:120, completed:true },
  { id:25, category:"Coding", title:"Ship personal knowledge graph alpha", xp:900, completed:false },
  { id:26, category:"Coding", title:"Build a custom crawler + indexer", xp:1000, completed:false },
  { id:27, category:"Travel", title:"Roadtrip along the Kenyan coast", xp:300, completed:false },
  { id:28, category:"Creative", title:"Design event concept for a large client", xp:550, completed:true },
  { id:29, category:"Health", title:"Complete a season of football matches", xp:400, completed:false },
  { id:30, category:"Community", title:"Mentor 3 junior devs", xp:600, completed:false },
  { id:31, category:"Legacy", title:"Start a scholarship fund", xp:1200, completed:false },
  { id:32, category:"Personal", title:"Publish a personal essay", xp:200, completed:true },
  { id:33, category:"Business", title:"Reach first $10k revenue month", xp:1500, completed:false },
  { id:34, category:"Learning", title:"Learn cinematography lighting", xp:300, completed:false },
  { id:35, category:"Coding", title:"Open-source a small useful tool", xp:250, completed:true },
  { id:36, category:"Travel", title:"Visit a global tech hub (eg. Berlin)", xp:800, completed:false },
  { id:37, category:"Creative", title:"Create 30-day content sprint", xp:350, completed:false },
  { id:38, category:"Startup", title:"Pitch to 10 investors", xp:1000, completed:false },
  { id:39, category:"Film", title:"Hire composer for score", xp:220, completed:false },
  { id:40, category:"Personal", title:"Host a party with Nexus Creations", xp:450, completed:true },
  { id:41, category:"Coding", title:"Implement personal search engine UI", xp:600, completed:false },
  { id:42, category:"Health", title:"30-day strength program", xp:280, completed:false },
  { id:43, category:"Legacy", title:"Create a visual archive of films", xp:400, completed:false },
  { id:44, category:"Networking", title:"Collaborate with a filmmaker abroad", xp:650, completed:false },
  { id:45, category:"Business", title:"Document SOPs for Nexus Creations", xp:300, completed:true },
  { id:46, category:"Coding", title:"Prototype Satellite Tracker", xp:950, completed:false },
  { id:47, category:"Creative", title:"Make a festival-ready trailer", xp:500, completed:false },
  { id:48, category:"Personal", title:"Revisit childhood town and make a short", xp:350, completed:false },
  { id:49, category:"Community", title:"Launch a coding bootcamp scholarship", xp:1100, completed:false },
  { id:50, category:"Legacy", title:"Be featured in major publication", xp:1200, completed:false },
  { id:51, category:"Fun", title:"Win a local football tournament", xp:700, completed:false },
  { id:52, category:"Creative", title:"Build the visual bible for 'The Forgotten Ones'", xp:800, completed:false },
  { id:53, category:"Startup", title:"Automate onboarding flow for clients", xp:350, completed:false },
  { id:54, category:"Personal", title:"Finish award-worthy short film", xp:1400, completed:false }
];
